FROM debian:jessie
RUN apt-get update -y && apt-get install -yy libevent-2.0-5 libevent-pthreads-2.0-5 libssl1.0.0 libcrypto++9
RUN mkdir -p /opt/gamewatcher
WORKDIR /opt/gamewatcher
COPY ./gamewatcher .
COPY ./config.json .
COPY ./public ./public
RUN useradd gamewatcher
RUN mkdir -p /etc/vibe/
RUN echo '{"user": "gamewatcher","group": "gamewatcher"}"' > /etc/vibe/vibe.conf
EXPOSE 27080
CMD ./gamewatcher
