FROM debian:jessie
RUN apt-get update -y && \
    apt-get install -yy --no-install-recommends libevent-2.0-5 libevent-pthreads-2.0-5 libssl1.0.0 libcrypto++9 && \
    apt-get -y clean && \
    rm -rf /var/cache/apt/* /var/lib/apt/lists/*
RUN mkdir -p /opt/gamewatcher
WORKDIR /opt/gamewatcher
COPY ./gamewatcher .
COPY ./config.json .
COPY ./public ./public
RUN useradd gamewatcher
RUN mkdir -p /etc/vibe/
RUN echo '{"user": "gamewatcher","group": "gamewatcher"}"' > /etc/vibe/vibe.conf
EXPOSE 27080
ENTRYPOINT ["./gamewatcher"]
